import "server-only";

import { passwordsMatch } from "./session";

/**
 * EPIC 9-1: who may reach the Workflow runtime's queue endpoints
 * (`/.well-known/workflow/v1/flow` and `/step`, generated by
 * `withWorkflow`).
 *
 * Those endpoints are the queue's delivery target: whoever can POST to
 * them can run workflow code. `flow` even accepts a `runInput` in the
 * message and *creates* the run if it doesn't exist yet (the runtime's
 * "resilient start"), so one unauthenticated POST could start
 * `processMeetingWorkflow` for any job id, bypassing `lockJobStart` —
 * re-transcribing (AI cost) and, for a B job, mailing the minutes again.
 *
 * - Vercel (`@workflow/world-vercel`): the platform only lets Vercel
 *   Queue invoke these functions (they are queue consumers, not public
 *   routes; see node_modules/workflow/docs/deploying/world/vercel-world.mdx,
 *   "Consumer function security"). So they pass here unchanged.
 * - Local (`@workflow/world-local`, `npm run dev` / `npm run local`):
 *   the queue just `fetch`es `http://localhost:<port>/.well-known/...`
 *   with no credential at all ("No authentication — suitable only for
 *   local development"), while this app listens on 0.0.0.0 for phone
 *   testing. Anyone on the LAN could forge a delivery. The runtime's only
 *   knob is WORKFLOW_LOCAL_BASE_URL (the base the queue delivers to), so
 *   we put an unguessable path segment in it:
 *
 *       WORKFLOW_LOCAL_BASE_URL=http://localhost:3000/_workflow/<secret>
 *
 *   The queue then calls `/_workflow/<secret>/.well-known/workflow/v1/flow`;
 *   `proxy.ts` checks the secret and rewrites to the real route. A direct
 *   request to `/.well-known/workflow/...` is refused. `scripts/dev.mjs`
 *   and `scripts/local.mjs` generate a fresh secret per server start;
 *   playwright.config.ts sets a fixed test one.
 *
 * `/.well-known/workflow/v1/webhook/<token>` (createWebhook's public
 * resume URL, token-only auth) is refused everywhere: nothing here uses
 * webhooks.
 */

export const WORKFLOW_ROUTE_BASE = "/.well-known/workflow/";
/** Path prefix of the local queue's delivery URL (before the secret). */
export const WORKFLOW_TUNNEL_PREFIX = "/_workflow/";
export const MIN_WORKFLOW_TUNNEL_SECRET_LENGTH = 32;

/** The only runtime endpoints the queue delivers to. */
const QUEUE_ENDPOINTS = new Set([
  "/.well-known/workflow/v1/flow",
  "/.well-known/workflow/v1/step",
]);

const TUNNEL_BASE_PATTERN = new RegExp(
  `^/_workflow/([A-Za-z0-9_-]{${MIN_WORKFLOW_TUNNEL_SECRET_LENGTH},256})/?$`,
);

type Env = Record<string, string | undefined>;

export type WorkflowRouteDecision =
  /** Not a workflow path; the normal cookie rules apply. */
  | { kind: "none" }
  /** Hand to the route as is (Vercel: platform-protected consumer). */
  | { kind: "pass" }
  /** Verified local queue delivery; serve it from `pathname`. */
  | { kind: "rewrite"; pathname: string }
  /** Refuse (404, no hint why). */
  | { kind: "deny" };

/** Same rule as `@workflow/utils`' `usesVercelWorld`. */
export function usesVercelWorld(env: Env = process.env): boolean {
  const target =
    env.WORKFLOW_TARGET_WORLD || (env.VERCEL_DEPLOYMENT_ID ? "vercel" : "local");
  return target === "vercel" || target === "@workflow/world-vercel";
}

let loggedMissingTunnel = false;

function logMissingTunnelOnce(): void {
  if (loggedMissingTunnel) return;
  loggedMissingTunnel = true;
  console.error(
    `[workflow] WORKFLOW_LOCAL_BASE_URL is not set to http://localhost:<port>${WORKFLOW_TUNNEL_PREFIX}<secret of ${MIN_WORKFLOW_TUNNEL_SECRET_LENGTH}+ characters>. Workflow queue requests are refused; start the server with \`npm run dev\` or \`npm run local\`.`,
  );
}

/**
 * The secret path segment from WORKFLOW_LOCAL_BASE_URL, or `null` when
 * it's missing or doesn't have the `/_workflow/<32+ chars>` shape.
 */
export function readWorkflowTunnelSecret(env: Env = process.env): string | null {
  const raw = env.WORKFLOW_LOCAL_BASE_URL;
  if (!raw) return null;
  let pathname: string;
  try {
    const url = new URL(raw);
    if (url.search || url.hash) return null;
    pathname = url.pathname;
  } catch {
    return null;
  }
  return pathname.match(TUNNEL_BASE_PATTERN)?.[1] ?? null;
}

export function decideWorkflowRoute(
  pathname: string,
  env: Env = process.env,
): WorkflowRouteDecision {
  const vercel = usesVercelWorld(env);

  if (pathname.startsWith(WORKFLOW_ROUTE_BASE)) {
    if (vercel && QUEUE_ENDPOINTS.has(pathname)) return { kind: "pass" };
    // Local world: the real queue never calls this path directly (it goes
    // through the tunnel below), so anything arriving here was forged —
    // or the tunnel isn't configured, which the log line says.
    if (!vercel && readWorkflowTunnelSecret(env) === null) {
      logMissingTunnelOnce();
    }
    return { kind: "deny" };
  }

  if (!pathname.startsWith(WORKFLOW_TUNNEL_PREFIX)) return { kind: "none" };

  // Everything under /_workflow/ is ours: deny whatever doesn't verify
  // rather than letting it fall through to other routes.
  if (vercel) return { kind: "deny" };
  const expected = readWorkflowTunnelSecret(env);
  if (expected === null) {
    logMissingTunnelOnce();
    return { kind: "deny" };
  }

  const rest = pathname.slice(WORKFLOW_TUNNEL_PREFIX.length);
  const slash = rest.indexOf("/");
  if (slash < 0) return { kind: "deny" };
  const presented = rest.slice(0, slash);
  const target = rest.slice(slash);
  // Constant time: hash both sides, then timingSafeEqual.
  if (!passwordsMatch(presented, expected)) return { kind: "deny" };
  if (!QUEUE_ENDPOINTS.has(target)) return { kind: "deny" };
  return { kind: "rewrite", pathname: target };
}
